volumes:
  pg_data_production:
  static_volume:
  media_volume: # M

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: mashuup/kittygram_backend
    env_file: .env
    entrypoint: ["/app/entrypoint.sh"]
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media  # M
  frontend:
    image: mashuup/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: mashuup/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles
      - media_volume:/app/media  # M
    ports:
      - 9000:80